"""
Django settings for voting_system project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from decouple import config
import cloudinary

# cloudinary imports
import cloudinary.uploader
import cloudinary.api


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# These values can be overridden with environment variables (e.g. on Render's
# dashboard) without touching code. The hardcoded fallbacks below are the
# values already in use, kept only so nothing breaks if the env vars aren't
# set yet — they are exposed in git history and should be rotated and moved
# to env vars as soon as possible.
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-a(1(wp+^gn^fi64_wz9)qp*9257nxj^s$c-l4@6asjbl^$n)l*'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=True in a local .env file for development; defaults to off so a
# crash never leaks secrets/stack traces to voters on the live site.
DEBUG = config('DEBUG', default=False, cast=bool)

# ".vercel.app" (leading dot) matches any Vercel preview/production subdomain.
# Override/extend with a comma-separated ALLOWED_HOSTS env var for a custom domain.
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default="nabes-bme-election.onrender.com,www.nabes-bme-election.onrender.com,.vercel.app,127.0.0.1,localhost",
    cast=lambda v: [h.strip() for h in v.split(',') if h.strip()]
)


# Database
DATABASES = {
    # neon.tech
    ## Email: thewatch2d@gmail.com
    'default': dj_database_url.parse(
        config(
            'DATABASE_URL',
            default='postgresql://neondb_owner:npg_FwbGQ8WoVn1r@ep-odd-glitter-ad4ndj5m-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
        )
    ),
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # custom apps
    'voting.apps.VotingConfig',

    # other packages
    'widget_tweaks',

    # cloudinary 
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'voting_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


cloudinary.config(
    cloud_name = config('CLOUDINARY_CLOUD_NAME', default="dgzjegrcm"),
    api_key = config('CLOUDINARY_API_KEY', default="275554513554491"),
    api_secret = config('CLOUDINARY_API_SECRET', default="sdA3bKAcsECuooRNa1Fu1lcjdEE")
)

WSGI_APPLICATION = 'voting_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# Kept intentionally minimal: this is a low-stakes department election used by
# non-technical students, so we only enforce a short minimum length rather
# than rejecting simple/numeric passwords, which caused confusing failures.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 4},
    },
]
AUTH_USER_MODEL = 'voting.Student'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Where `collectstatic` (run by setup.sh) writes output for Vercel's
# @vercel/static-build step — matches vercel.json's distDir/static route.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
