# Generated by Django 5.2.4 on 2026-08-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0009_alter_position_importance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Election Setting",
                "verbose_name_plural": "Election Settings",
            },
        ),
        migrations.AlterField(
            model_name="position",
            name="importance",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 - Very High"),
                    (2, "2 - High"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5 - Medium"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Low"),
                    (11, "11 - Very Low"),
                    (12, "12 - Lowest"),
                ]
            ),
        ),
    ]
